typography_spectrum: 0.8659098774660379
color:
  brandStrength: 0.3039015990216285
  lightness: 0.23720112699083984
  saturation: 0.7613195492886007
  rhythmicContrast: 0.4261853531934321
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
layout_spectrum: 0.6781929607968777
author:
  email: contacto@filum.ws
  url: 'http://filum.ws'
  name: Tell Us what is your need
name: Filum
title: integral solutions
description: Inhabit + wit = Happiness
