typography_spectrum: 0.6198640370275825
color:
  brandStrength: 0.05087525490671396
  lightness: 0.38822241593152285
  saturation: 0.5144269859883934
  rhythmicContrast: 0.09139251173473895
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.93463200237602
author:
  email: contacto@filum.ws
  url: 'http://filum.ws'
  name: Tell Us what is your need
name: Filum
title: integral solutions
description: Inhabit + wit = Happiness
